
services:
  - type: web
    name: asistente-deportivo-ia
    runtime: python3
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: WEBHOOK_URL
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false  
      - key: TELEGRAM_CHAT_ID
        sync: false
